export default {
  USER_JOIN: "USER_JOIN",
  USER_JOINED: "USER_JOINED",
  USER_LEFT: "USER_LEFT",
  SET_ERROR: "SET_ERROR",
  ADD_MESSAGE: "ADD_MESSAGE",
  SET_PROFILE_IMAGE: "SET_PROFILE_IMAGE",
  SET_IMAGE: "SET_IMAGE",
  RESET: "RESET"
};
